- name: Initializing the custom variables used in branching  
  vars:
  set_fact:
    pool_statuses: {}
  tags:
    - post-upgrade-guests



- name: COLLECT BIG-IP ltm Pools for "{{ item }}" using the FACTS module
  bigip_device_info:
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
    gather_subset:
      - ltm-pools
  register: pools
  tags:
    - post-upgrade-guests

- name: Extracting the status of the pools
  set_fact:
    pool_statuses: "{{ pool_statuses|default({}) | combine({'poolName':item.name,'status':item.availability_status})  }}"
  loop: "{{ pools.ltm_pools }}"
  tags:
    - post-upgrade-guests


- name: Copy output to file
  copy:
    content: "{{ pool_statuses }}"
    dest: "{{ TMP }}/{{ item }}.json"
  tags:
    - post-upgrade-guests