- name: VCMP guest deployed mode "{{ item }}"
  bigip_vcmp_guest:
    name: "{{ item }}"
    state: present
    provider: 
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  register: result
  tags:
    - upgrade-hosts


